name: network_topology_gis
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  loading_animation_widget: ^1.2.0+4
  location: ^5.0.3
  dropdown_button2: ^2.3.9
  dio: ^5.0.0
  eva_icons_flutter: ^3.1.0
  json_annotation: ^4.9.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.6.1



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/
    # - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  
  fonts:
    - family: Manrope Regular
      fonts:
        - asset: fonts/manrope-regular.otf


    - family: Manrope Bold
      fonts:
        - asset: fonts/manrope-bold.otf


    - family: Manrope Medium
      fonts:
        - asset: fonts/manrope-medium.otf

        
    - family: Manrope Thin
      fonts:
        - asset: fonts/manrope-thin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
